//exit
document.getElementById("btn5").addEventListener("click",function(){
  window.close();
});
//giveup
document.getElementById("btn6").addEventListener("click",function(){
  judge_giveup();
});
document.getElementById("w1").addEventListener("click",function(){
  chk_wall(1,1,1)
  });
document.getElementById("w2").addEventListener("click",function(){
  chk_wall(1,2,1)
  });
document.getElementById("w3").addEventListener("click",function(){
  chk_wall(1,3,1)
  });
document.getElementById("w4").addEventListener("click",function(){
  chk_wall(1,4,1)
  });
document.getElementById("w5").addEventListener("click",function(){
  chk_wall(1,5,1)
  });
document.getElementById("w6").addEventListener("click",function(){
  chk_wall(1,6,1)
  });
document.getElementById("w7").addEventListener("click",function(){
  chk_wall(1,7,1)
  });
document.getElementById("w8").addEventListener("click",function(){
  chk_wall(1,8,1)
  });
document.getElementById("w9").addEventListener("click",function(){
  chk_wall(2,1,1)
  });
document.getElementById("w10").addEventListener("click",function(){
  chk_wall(2,2,1)
  });
document.getElementById("w11").addEventListener("click",function(){
  chk_wall(2,3,1)
  });
document.getElementById("w12").addEventListener("click",function(){
  chk_wall(2,4,1)
  });
document.getElementById("w13").addEventListener("click",function(){
  chk_wall(2,5,1)
  });
document.getElementById("w14").addEventListener("click",function(){
  chk_wall(2,6,1)
  });
document.getElementById("w15").addEventListener("click",function(){
  chk_wall(2,7,1)
  });
document.getElementById("w16").addEventListener("click",function(){
  chk_wall(2,8,1)
  });
document.getElementById("w17").addEventListener("click",function(){
  chk_wall(3,1,1)
  });
document.getElementById("w18").addEventListener("click",function(){
  chk_wall(3,2,1)
  });
document.getElementById("w19").addEventListener("click",function(){
  chk_wall(3,3,1)
  });
document.getElementById("w20").addEventListener("click",function(){
  chk_wall(3,4,1)
  });
document.getElementById("w21").addEventListener("click",function(){
  chk_wall(3,5,1)
  });
document.getElementById("w22").addEventListener("click",function(){
  chk_wall(3,6,1)
  });
document.getElementById("w23").addEventListener("click",function(){
  chk_wall(3,7,1)
  });
document.getElementById("w24").addEventListener("click",function(){
  chk_wall(3,8,1)
  });
document.getElementById("w25").addEventListener("click",function(){
  chk_wall(4,1,1)
  });
document.getElementById("w26").addEventListener("click",function(){
  chk_wall(4,2,1)
  });
document.getElementById("w27").addEventListener("click",function(){
  chk_wall(4,3,1)
  });
document.getElementById("w28").addEventListener("click",function(){
  chk_wall(4,4,1)
  });
document.getElementById("w29").addEventListener("click",function(){
  chk_wall(4,5,1)
  });
document.getElementById("w30").addEventListener("click",function(){
  chk_wall(4,6,1)
  });
document.getElementById("w31").addEventListener("click",function(){
  chk_wall(4,7,1)
  });
document.getElementById("w32").addEventListener("click",function(){
  chk_wall(4,8,1)
  });
document.getElementById("w33").addEventListener("click",function(){
  chk_wall(5,1,1)
  });
document.getElementById("w34").addEventListener("click",function(){
  chk_wall(5,2,1)
  });
document.getElementById("w35").addEventListener("click",function(){
  chk_wall(5,3,1)
  });
document.getElementById("w36").addEventListener("click",function(){
  chk_wall(5,4,1)
  });
document.getElementById("w37").addEventListener("click",function(){
  chk_wall(5,5,1)
  });
document.getElementById("w38").addEventListener("click",function(){
  chk_wall(5,6,1)
  });
document.getElementById("w39").addEventListener("click",function(){
  chk_wall(5,7,1)
  });
document.getElementById("w40").addEventListener("click",function(){
  chk_wall(5,8,1)
  });
document.getElementById("w41").addEventListener("click",function(){
  chk_wall(6,1,1)
  });
document.getElementById("w42").addEventListener("click",function(){
  chk_wall(6,2,1)
  });
document.getElementById("w43").addEventListener("click",function(){
  chk_wall(6,3,1)
  });
document.getElementById("w44").addEventListener("click",function(){
  chk_wall(6,4,1)
  });
document.getElementById("w45").addEventListener("click",function(){
  chk_wall(6,5,1)
});
document.getElementById("w46").addEventListener("click",function(){
  chk_wall(6,6,1)
  });
document.getElementById("w47").addEventListener("click",function(){
  chk_wall(6,7,1)
  });
document.getElementById("w48").addEventListener("click",function(){
  chk_wall(6,8,1)
  });
document.getElementById("w49").addEventListener("click",function(){
  chk_wall(7,1,1)
  });
document.getElementById("w50").addEventListener("click",function(){
  chk_wall(7,2,1)
  });
document.getElementById("w51").addEventListener("click",function(){
  chk_wall(7,3,1)
 });
document.getElementById("w52").addEventListener("click",function(){
  chk_wall(7,4,1)
  });
document.getElementById("w53").addEventListener("click",function(){
  chk_wall(7,5,1)
  });
document.getElementById("w54").addEventListener("click",function(){
  chk_wall(7,6,1)
  });
document.getElementById("w55").addEventListener("click",function(){
  chk_wall(7,7,1)
  });
document.getElementById("w56").addEventListener("click",function(){
  chk_wall(7,8,1)
  });
document.getElementById("w57").addEventListener("click",function(){
  chk_wall(8,1,1)
  });
document.getElementById("w58").addEventListener("click",function(){
  chk_wall(8,2,1)
  });
document.getElementById("w59").addEventListener("click",function(){
  chk_wall(8,3,1)
  });
document.getElementById("w60").addEventListener("click",function(){
  chk_wall(8,4,1)
  });
document.getElementById("w61").addEventListener("click",function(){
  chk_wall(8,5,1)
  });
document.getElementById("w62").addEventListener("click",function(){
  chk_wall(8,6,1)
  });
document.getElementById("w63").addEventListener("click",function(){
  chk_wall(8,7,1)
  });
document.getElementById("w64").addEventListener("click",function(){
  chk_wall(8,8,1)
  });

document.getElementById("k1").addEventListener("click",function(){
  chk_wall(1,1,2)
  });
document.getElementById("k2").addEventListener("click",function(){
  chk_wall(1,2,2)
  });
document.getElementById("k3").addEventListener("click",function(){
  chk_wall(1,3,2)
  });
document.getElementById("k4").addEventListener("click",function(){
  chk_wall(1,4,2)
  });
document.getElementById("k5").addEventListener("click",function(){
  chk_wall(1,5,2)
  });
document.getElementById("k6").addEventListener("click",function(){
  chk_wall(1,6,2)
  });
document.getElementById("k7").addEventListener("click",function(){
  chk_wall(1,7,2)
  });
document.getElementById("k8").addEventListener("click",function(){
  chk_wall(1,8,2)
  });
document.getElementById("k9").addEventListener("click",function(){
  chk_wall(2,1,2)
  });
document.getElementById("k10").addEventListener("click",function(){
  chk_wall(2,2,2)
  });
document.getElementById("k11").addEventListener("click",function(){
  chk_wall(2,3,2)
  });
document.getElementById("k12").addEventListener("click",function(){
  chk_wall(2,4,2)
  });
document.getElementById("k13").addEventListener("click",function(){
  chk_wall(2,5,2)
  });
document.getElementById("k14").addEventListener("click",function(){
  chk_wall(2,6,2)
  });
document.getElementById("k15").addEventListener("click",function(){
  chk_wall(2,7,2)
  });
document.getElementById("k16").addEventListener("click",function(){
  chk_wall(2,8,2)
  });
document.getElementById("k17").addEventListener("click",function(){
  chk_wall(3,1,2)
  });
document.getElementById("k18").addEventListener("click",function(){
  chk_wall(3,2,2)
  });
document.getElementById("k19").addEventListener("click",function(){
  chk_wall(3,3,2)
  });
document.getElementById("k20").addEventListener("click",function(){
  chk_wall(3,4,2)
  });
document.getElementById("k21").addEventListener("click",function(){
  chk_wall(3,5,2)
  });
document.getElementById("k22").addEventListener("click",function(){
  chk_wall(3,6,2)
  });
document.getElementById("k23").addEventListener("click",function(){
  chk_wall(3,7,2)
  });
document.getElementById("k24").addEventListener("click",function(){
  chk_wall(3,8,2)
  });
document.getElementById("k25").addEventListener("click",function(){
  chk_wall(4,1,2)
  });
document.getElementById("k26").addEventListener("click",function(){
  chk_wall(4,2,2)
  });
document.getElementById("k27").addEventListener("click",function(){
  chk_wall(4,3,2)
  });
document.getElementById("k28").addEventListener("click",function(){
  chk_wall(4,4,2)
  });
document.getElementById("k29").addEventListener("click",function(){
  chk_wall(4,5,2)
  });
document.getElementById("k30").addEventListener("click",function(){
  chk_wall(4,6,2)
  });
document.getElementById("k31").addEventListener("click",function(){
  chk_wall(4,7,2)
  });
document.getElementById("k32").addEventListener("click",function(){
  chk_wall(4,8,2)
  });
document.getElementById("k33").addEventListener("click",function(){
  chk_wall(5,1,2)
  });
document.getElementById("k34").addEventListener("click",function(){
  chk_wall(5,2,2)
  });
document.getElementById("k35").addEventListener("click",function(){
  chk_wall(5,3,2)
  });
document.getElementById("k36").addEventListener("click",function(){
  chk_wall(5,4,2)
  });
document.getElementById("k37").addEventListener("click",function(){
  chk_wall(5,5,2)
  });
document.getElementById("k38").addEventListener("click",function(){
  chk_wall(5,6,2)
  });
document.getElementById("k39").addEventListener("click",function(){
  chk_wall(5,7,2)
  });
document.getElementById("k40").addEventListener("click",function(){
  chk_wall(5,8,2)
  });
document.getElementById("k41").addEventListener("click",function(){
  chk_wall(6,1,2)
  });
document.getElementById("k42").addEventListener("click",function(){
  chk_wall(6,2,2)
  });
document.getElementById("k43").addEventListener("click",function(){
  chk_wall(6,3,2)
  });
document.getElementById("k44").addEventListener("click",function(){
  chk_wall(6,4,2)
  });
document.getElementById("k45").addEventListener("click",function(){
  chk_wall(6,5,2)
  });
document.getElementById("k46").addEventListener("click",function(){
  chk_wall(6,6,2)
  });
document.getElementById("k47").addEventListener("click",function(){
  chk_wall(6,7,2)
  });
document.getElementById("k48").addEventListener("click",function(){
  chk_wall(6,8,2)
  });
document.getElementById("k49").addEventListener("click",function(){
  chk_wall(7,1,2)
  });
document.getElementById("k50").addEventListener("click",function(){
  chk_wall(7,2,2)
  });
document.getElementById("k51").addEventListener("click",function(){
  chk_wall(7,3,2)
  });
document.getElementById("k52").addEventListener("click",function(){
  chk_wall(7,4,2)
  });
document.getElementById("k53").addEventListener("click",function(){
  chk_wall(7,5,2)
  });
document.getElementById("k54").addEventListener("click",function(){
  chk_wall(7,6,2)
  });
document.getElementById("k55").addEventListener("click",function(){
  chk_wall(7,7,2)
  });
document.getElementById("k56").addEventListener("click",function(){
  chk_wall(7,8,2)
  });
document.getElementById("k57").addEventListener("click",function(){
  chk_wall(8,1,2)
  });
document.getElementById("k58").addEventListener("click",function(){
  chk_wall(8,2,2)
});
document.getElementById("k59").addEventListener("click",function(){
  chk_wall(8,3,2)
});
document.getElementById("k60").addEventListener("click",function(){
  chk_wall(8,4,2)
});
document.getElementById("k61").addEventListener("click",function(){
  chk_wall(8,5,2)
});
document.getElementById("k62").addEventListener("click",function(){
  chk_wall(8,6,2)
});
document.getElementById("k63").addEventListener("click",function(){
  chk_wall(8,7,2)
});
document.getElementById("k64").addEventListener("click",function(){
  chk_wall(8,8,2)
});
